version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - sam build
  post_build:
    commands:
      - echo Deploying application
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      - echo Build completed on `date`

artifacts:
  files:
    - template.yaml
    - .aws-sam/**/*